# Этот файл содержит GitHub Actions workflow для построения и выпуска релизов приложения AUI
name: Build #Объявление workflow
# Имя этого файла работы (workflow)

on:
  push:
    branches:
      - master
  pull_request:
#Триггеры запуска:

# При пуше на ветку master
# При создании PR (pull request)

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
# Оптимизация выполнения:

# Если запуск workflows для текущей ветки/PR существует — отменяется предыдущий
# pull_request.number — номер PR, github.ref — реф ветки (fallback)

# Переменные окружения
env:
  GIT_SUBMODULE_STRATEGY: recursive #Git будет клонировать подмодули рекурсивно

permissions:
  contents: write #Разрешение на запись контента (для создания релизов)

#Job 1: build-desktop
jobs:
  build-desktop:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest] #Запуск на ОС, указанной в матрице (сейчас только Ubuntu)
    # Сборка исходного кода    
    steps:
      - name: Fetch sources
        uses: actions/checkout@v4 #Клонирование репозитория с помощью GitHub Action v4

      # Cache AUI boot directory  Кэширование зависимостей AUI.BOOT
      - name: Cache AUI.BOOT deps
        id: cache-aui-boot
        uses: actions/cache@v3
        env:
          cache-name: aui-boot
        with:
          path: ~/.aui #Путь к .aui — директория с кэшируемыми зависимостями
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/CMakeLists.txt') }} #Key формируется из: ОС + имя кэша + хеш всех CMakeLists.txt (если изменили CMake → берём из кэша)
          #Restore-keys — для частичного восстановления кэша при изменении части файлов
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
#Установка зависимостей по ОС
      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: brew install cmake ninja

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install \
          pkg-config \
          libglew-dev \
          zlib1g-dev \
          libssl-dev \
          libcrypt-dev \
          libcurl4-openssl-dev \
          libgtk-4-dev \
          libadwaita-1-dev \
          libdbus-1-dev \
          libfontconfig-dev \
          ninja-build \
          libpulse-dev \
          gperf

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        run: choco install innosetup
# Настройка компилятора
      - name: Setup Clang 22 (Linux)
        if: runner.os == 'Linux'
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 22 all
          echo "CC=clang-22" >> $GITHUB_ENV
          echo "CXX=clang++-22" >> $GITHUB_ENV

      - name: Setup Clang (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install llvm -y
          echo "CC=clang" >> $env:GITHUB_ENV
          echo "CXX=clang++" >> $env:GITHUB_ENV
#Конфигурация CMake
      - name: Configure CMake
        run: cmake -G "Ninja" -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=RelWithDebInfo ${{ runner.os == 'Windows' && '-DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded' || '' }} -DAUI_INSTALL_RUNTIME_DEPENDENCIES=TRUE

      - name: Build Project
        run: cmake --build ${{github.workspace}}/build --config RelWithDebInfo

      - name: Build Tests
        run: cmake --build ${{github.workspace}}/build --config RelWithDebInfo --target Tests

      - name: Run Tests (Windows)
        if: runner.os == 'Windows'
        working-directory: ${{github.workspace}}/build/bin
        run: ${{github.workspace}}/build/bin/Tests.exe --gtest_filter=-"*Integration*"

      - name: Run Tests (Linux and macOS)
        if: runner.os != 'Windows'
        working-directory: ${{github.workspace}}/build/bin
        run: ${{github.workspace}}/build/bin/Tests --gtest_filter=-"*Integration*"

      - name: Pack Windows Setup
        if: runner.os == 'Windows'
        working-directory: ${{github.workspace}}/build
        run: |
          cmake . -DAUI_APP_PACKAGING=INNOSETUP
          cmake --build . --config RelWithDebInfo
          cpack . -CRelWithDebInfo -B artifacts

      - name: Pack Portable
        working-directory: ${{github.workspace}}/build
        run: |
          cmake . -DAUI_APP_PACKAGING=${{ runner.os == 'Linux' && 'AUI_PORTABLE_TGZ' || 'AUI_PORTABLE_ZIP' }}
          cmake --build . --config RelWithDebInfo
          cpack . -CRelWithDebInfo -B artifacts

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          path: ${{github.workspace}}/build/artifacts/*.*
          name: ${{ runner.os }}


  release-draft:
    runs-on: ubuntu-latest
    permissions: write-all
    if: github.event_name != 'pull_request'
    needs: [ build-desktop ]
    name: "Release draft"
    steps:
      - name: Fetch sources
        uses: actions/checkout@v4

      - name: Extract version
        run: |
          VERSION=$(grep -Po '[0-9\.]+(?= # CI_PROJECT_VERSION)' CMakeLists.txt)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "VERSION = $VERSION"

      # Remove old release drafts
      - name: Remove Old Release Drafts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api repos/{owner}/{repo}/releases \
            --jq '.[] | select(.draft == true) | .id' \
            | xargs -I '{}' gh api -X DELETE repos/{owner}/{repo}/releases/{}

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: 'true'

      - name: Create Release Draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "v${{ env.VERSION }}" \
            --draft \
            --title "v${{ env.VERSION }}" \
            --target $GITHUB_SHA \
            artifacts/*.*
